18-feature-enhancement-shorten-builder-module
hhlim12/STATE-BATCH pull request #42
Opened 2022-10-25 09:05 UTC by uedar

2022-10-25 13:30 UTC, kimrojas requested changes

2022-10-25 13:30 UTC, kimrojas commented on statebatch/statebatch/build.py
>  def build(atom_to_run, input_data, system_spec, calc_name, file_prefix=None):
change code
`system_spec.get("type") == "Surface" or system_spec.get("type") == "Adsorption"`
to
`elif system_spec.get("type") in ["Surface", "Adsorption"]:`

2022-10-25 13:30 UTC, kimrojas commented on statebatch/statebatch/build.py
>          facet = str(atom_to_run["Facet"])
Can you provide a some kind of test file ?

2022-10-26 05:15 UTC, uedar commented on statebatch/statebatch/build.py
>  def build(atom_to_run, input_data, system_spec, calc_name, file_prefix=None):
Thank you. I modified the code as you suggested.

2022-10-26 05:16 UTC, uedar commented on statebatch/statebatch/build.py
>          facet = str(atom_to_run["Facet"])
Are the test files in the `examples` directory not sufficient?
Or is it better to add test cases in `/tests/test_build.py`?

2022-10-26 05:16 UTC, uedar commented on statebatch/statebatch/build.py
>          facet = str(atom_to_run["Facet"])
Are the test files in the `examples` directory not sufficient?
Or is it better to add test cases in `/tests/test_build.py`?

2022-10-26 12:07 UTC, kimrojas approved these changes
Looks good. Ok for merge. @uedar

2022-10-26 12:07 UTC, merged