Harry/small updates on archiver
hhlim12/STATE-BATCH pull request #62
Opened 2022-11-17 12:22 UTC by hhlim12

I wrote some updates on the archiving function:
1. Now the archive option in the yaml file is used. Currently only two keys are used, namely the name format (can be unique ID or custom string) and the file format (can be json or db file). More keywords are possible in the future.
2. Fix a bug in QE archiver:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/77390746/202443748-7768dc4c-cad3-482b-aab1-479f6ff279f8.png">

Previously `calc` is not define in the if condition for QE. I think it will result in error.
3. Minor update on the printing status for parallel jobscript: print ARCHIVED to log file after finish archiving.
<img width="741" alt="image" src="https://user-images.githubusercontent.com/77390746/202444307-44b83eff-a98d-4094-943f-2b9f36e77993.png">

Below is the yaml and csv file I used for quick testing.

```yaml
---
###################################################################################
#Configuration file used to run high-troughput calculation using STATE (or QE) code
#v.0.1
###################################################################################

comp_spec:
     csv_loc: ./list_of_single_atoms.csv # Location of csv file
     pw_loc: /sqfs/home/u6b589/STATE/state-5.6.8/src  # Location of executable file
     pw_name: STATE
     mpi_command: "mpirun"
     pseudo_loc: /sqfs/home/u6b589/STATE/gncpp_pack   # Location of pseudopotentials directory
     n_cpus: 4                          # Number of allocated cpus for each calculation
     n_nodes: 1                          # Number of allocated node(s) for each calculation
     prefix: atom_run                         # Prefix for the directory name
     file_prefix: state
system_spec:
     type: Atom                        # One of the following: Atom, Bulk, Molecule, Surface, Adsorption
     fix_params:
        Vacuum: 10.0                   # If type is Atom, Molecule, or Surface
#        Alat: from_ase                 # If type is Bulk or surface
#        Size: (1,1,1)                  # If type is Surface
#     vary_params:

dft_spec:
    name: STATE                          # Can be STATE or QE
    fix_params:                          # List of fixed parameters for each calculation
        "KPOINT_MESH": [1, 1, 1]
        "KPOINT_SHIFT": ["OFF", "OFF", "OFF"]
        "NEG": 8
        "NSCF": 1000
        "TASK": "SCF"
        "WAY_MIX": 6
        "MIX_WHAT": 1
        "KBXMIX": 30
        "MIX_ALPHA": 0.5
        "WIDTH": -0.0020
        "XCTYPE": "ggapbe"
        "EDELTA": 0.1
    vary_params:                         # List of STATE parameters to be read from csv file
        - "PSEUDOS"
        - "GMAX"
        - "GMAXP"

archive_option:
     name_format: unique_id                     # Name of archive file.
     file_format: json                    # Type of archive file. Can be json or db

```

and csv file:
```
Species,PSEUDOS,GMAX,GMAXP
H,H@pot.H_lda1,4,16
Li,Li@pot.Li_pbe1TM,4,16
Be,Be@pot.Be_pbe1TM,4,16
B,B@pot.B_pbe3,4,16
C,C@pot.C_pbe1,4,16
```

2022-11-18 06:58 UTC, kimrojas requested changes

2022-11-18 06:58 UTC, kimrojas commented on statebatch/statebatch/archiver.py
> +def prearchive(system_type, atoms_obj, atoms_dict, comp_spec, archive_option):
Thanks for adding this flexibility option. However, is it possible to apply some sort of defaults parameters fallback? For example if `archive_option` is not set the `name_format` and `file_format` will still be available.

Maybe this code snippet maybe useful

```python
# 1. Set the default of archive_option input variable to be an empty dictionary
# def prearchive(system_type, atoms_obj, atoms_dict, comp_spec, archive_option={}):

# 1. Create default dictionary
archive_option_default = {"name_format": "unique_id", "file_format": "json"}

# 2. Update archive_option with archive_option_default, 
# the following code will only add default values if it does not exist in archive option
for key, value in archive_option.items():
    archive_option.setdefault(key, value)
```

More info on the syntax [here](https://note.nkmk.me/en/python-dict-setdefault/)

2022-11-18 06:58 UTC, kimrojas commented on statebatch/statebatch/archiver.py
> +        if prerun_fname.split('.')[0] == 'unique_id':
This may be a little hard to follow (cause of the splitting). 
Instead can you change to the dictionary syntax ?
archive_option.get('name_format') 
archive_option.get('file_format')

2022-11-19 12:34 UTC, hhlim12 commented on statebatch/statebatch/archiver.py
> +        if prerun_fname.split('.')[0] == 'unique_id':
I modified the code like this in which I assigned more intuitive name for the variables: 
<img width="713" alt="image" src="https://user-images.githubusercontent.com/77390746/202850901-43e7d80f-58ba-4220-b4fa-c12dcfa75219.png">

I don't use `archive_option` dictionary because the only information passed to the archive() function is the name of prerun file (not the dictionary).

<img width="940" alt="image" src="https://user-images.githubusercontent.com/77390746/202851020-d4a8e315-f5d1-4b5f-b946-57a832e7c18c.png">

2022-11-19 12:34 UTC, hhlim12 commented on statebatch/statebatch/archiver.py
> +def prearchive(system_type, atoms_obj, atoms_dict, comp_spec, archive_option):
Thanks for the nice suggestion!
I modified the `STATEbatch.py` as follow:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/77390746/202850702-c8d27880-0300-4af9-bbff-794c7e69b1c0.png">

I made a design in such a way that the archiving will be always done even though the `archive_option` is not specified. So if the `archive_option` is `None`, then the dictionary will take the default value. And if one of the key is not specified, that one will also take the default value.

2022-11-19 15:44 UTC, kimrojas commented on statebatch/statebatch/archiver.py
> +def prearchive(system_type, atoms_obj, atoms_dict, comp_spec, archive_option):
Thanks for the edit. I externalize the defaults setting of the archiver (in a commit I made to this branch). I just created a function that returns the user's archive_option with the default (mainly your code)

You can check the code diff here 
https://github.com/hhlim12/STATE-BATCH/compare/b5d032b..92e5d05

2022-11-19 15:47 UTC, kimrojas commented on statebatch/statebatch/archiver.py
> +        if prerun_fname.split('.')[0] == 'unique_id':
Thanks. I corrected a few things. The default of archive option should not be an empty dict
```python
def prearchive(system_type, atoms_obj, atoms_dict, comp_spec, archive_option={}):
# BECOMES
def prearchive(system_type, atoms_obj, atoms_dict, comp_spec, archive_option):
```

Also I just simplified a part of the code
```python
        # prerun_fname = prerun_fname.split('.')[0]
        # prerun_ftype = prerun_ftype.split('.')[-1]
        prerun_fname, prerun_ftype = prerun_fname.split('.')
```

2022-11-19 15:48 UTC, kimrojas commented on statebatch/statebatch/archiver.py
> +def prearchive(system_type, atoms_obj, atoms_dict, comp_spec, archive_option):
The old coode was is still in the code but in comments. If the changes are okay with you, I can merge it already.

2022-11-20 08:19 UTC, hhlim12 commented on statebatch/statebatch/archiver.py
> +        if prerun_fname.split('.')[0] == 'unique_id':
Thanks!

2022-11-20 08:49 UTC, hhlim12 commented on statebatch/statebatch/archiver.py
> +def prearchive(system_type, atoms_obj, atoms_dict, comp_spec, archive_option):
Hi Kurt, thanks for the suggestion. Even though the code is now cleaner, for me the assignment of the default parameters becomes less apparent. This is actually one of the reason I explicitly set the default in the `__init__` part of `STATEbatch.py`. Further, maybe we also need to set some default values for `comp_spec`, `dft_spec`, and `system_spec`. I planned to assign all default yaml key-values at similar location (e.g., `__init__`) so it would be more tractable. What do you think? Do you have second opinion?

2022-11-20 09:54 UTC, kimrojas commented on statebatch/statebatch/archiver.py
> +def prearchive(system_type, atoms_obj, atoms_dict, comp_spec, archive_option):
I see. I got your point. Maybe my approach isn't the best for this use then. Then how about, instead of externalizing the default adder, lets just add the default adder function within the STATEbatch? Or would explicit code be better ?

2022-11-20 10:37 UTC, hhlim12 commented on statebatch/statebatch/archiver.py
> +def prearchive(system_type, atoms_obj, atoms_dict, comp_spec, archive_option):
I think using the default adder function is nice idea. It address the centralization of the default parameter assignment and makes the code cleaner. Let me work on it..

2022-11-21 08:21 UTC, hhlim12 commented
Hi @kimrojas , I further modified the code to include the yaml and csv reader in separate function.
I named it `control.py`. Currently I don't have any idea on specifying the default value for `comp_spec`, `dft_spec`, or `system_spec`. But shall there are new default valus need to be specified, we can specify them in this `control.py` module.

<img width="701" alt="image" src="https://user-images.githubusercontent.com/77390746/202998590-de4ebf87-df3a-49ae-9db2-4ae225b9af44.png">

I also put a template for the reading task file aside from csv. Now I'm thinking to add alternative for task file (e.g., json file) to compensate the inflexibility of csv. We can put this feature also inside the `get_task` function in `control.py` module.

2022-11-22 07:38 UTC, merged