61 feature request platform information
hhlim12/STATE-BATCH pull request #67
Opened 2022-11-24 13:19 UTC by kimrojas

A `platform_info` query function is implemented. 
The function will get the cpu, os, etc, information from the node that run the calculation. 
The collected data will be added to the `data` in ase databe via update. It will basically append it. 

I created a `print_data.py` to print out the database of atom_run_0001 in single_atom. This script will be deleted in future updates.

2022-11-27 09:00 UTC, uedar requested changes

2022-11-27 09:00 UTC, uedar commented on statebatch/statebatch/archiver.py
> +    lscpu_dict = {key: val.strip() for key, val in [l.split(":") for l in lscpu_lines]}
```suggestion
    lscpu_dict = {key: val.strip() for key, val in [l.split(":", 1) for l in lscpu_lines]}
```

If there is more than one `:` on a line, error occurs.
I didn't have a problem with smith or squid, but just in case.

↓`lscpu` in docker
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          6
On-line CPU(s) list:             0-5
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       6
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           126
Model name:                      Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
Stepping:                        5
CPU MHz:                         2300.000
BogoMIPS:                        4600.00
L1d cache:                       288 KiB
L1i cache:                       192 KiB
L2 cache:                        3 MiB
L3 cache:                        48 MiB
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and use
                                 rcopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, STIBP: disabled
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtr
                                 r pge mca cmov pat pse36 clflush mmx fxsr sse s
                                 se2 ss ht pbe syscall nx pdpe1gb lm constant_ts
                                 c rep_good nopl xtopology nonstop_tsc cpuid pni
                                  pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xt
                                 pr pcid sse4_1 sse4_2 movbe popcnt aes xsave av
                                 x f16c rdrand hypervisor lahf_lm abm 3dnowprefe
                                 tch fsgsbase bmi1 avx2 bmi2 erms avx512f avx512
                                 cd xsaveopt arat
```

2022-11-28 13:06 UTC, kimrojas commented on statebatch/statebatch/archiver.py
> +    lscpu_dict = {key: val.strip() for key, val in [l.split(":") for l in lscpu_lines]}
@uedar  Thank you for the suggestion. The ":" bug has been fixed.

2022-11-28 13:09 UTC, uedar approved these changes
Thank you. Looks good to me.

2022-11-28 14:01 UTC, merged

2022-11-30 04:50 UTC, hhlim12 commented
@kimrojas , I have the following error when I run the calculation in SQUID.

<img width="1762" alt="image" src="https://user-images.githubusercontent.com/77390746/204710085-de7c129b-9223-49a5-937c-354b728d5af5.png">

Do you have any idea? Let me know if you need more information..

2022-11-30 05:55 UTC, kimrojas commented
> @kimrojas , I have the following error when I run the calculation in SQUID.
> 
> <img alt="image" width="1762" src="https://user-images.githubusercontent.com/77390746/204710085-de7c129b-9223-49a5-937c-354b728d5af5.png">
> 
> Do you have any idea? Let me know if you need more information..

Can you try to use `utf-8` instead of `ascii` ?

2022-11-30 06:02 UTC, hhlim12 commented
It works using utf-8 !

2022-11-30 07:01 UTC, kimrojas commented
@uedar 
> I didn't have a problem with smith or squid, but just in case.
May I ask if you also get the same problem as harry ?

2022-11-30 07:05 UTC, hhlim12 commented
When I tried to run the calculation in  login terminal (not node), it proceeds without error..

2022-11-30 07:22 UTC, uedar commented
Sorry, I only tried it in the login terminal...